### ISSUE TITLE
endian.h not found on Windows platform

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#12]
Added the following to ieee754.h:
> #elif (defined(_WIN32) || defined(_WIN64))
>     #include <winsock2.h>
>     #ifdef __GNUC__
>         #include <sys/param.h>
>     #endif

Fixes compilation.

**Comment by zaskar9** [comment]
I've extended your proposal and pushed it with the latest batch of bug fixes. With these changes, I can build liboberon on macOS (clang toolchain, arm64), Ubuntu Linux (GCC toolchain, arm64), and Windows 11 (MSVC toolchain, x64). Please test it on your setup and let me know if it works there too!

**Comment by tenko** [comment]
Confirmed to work fine now on MSYS2 CLANG64.
