### ISSUE TITLE
Output file argument not working

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#17]
I added/replaced the following lines to src\codegen\llvm\LLVMCodeGen.cpp from line 254:

>  std::string name = config_.getOutputFile();
>  if (name == "") {
>       name = path.replace_extension(ext).string();
>  }

This seems to fix the issue.

**Comment by zaskar9** [comment]
I think I never fully introduced that parameter. At some point, I want to make the command-line interface of `oberon-lang` as close to `clang` and `gcc` (not `msvc` 😎) as possible. As part of this change, I'm planning to replace the `--filetype` parameter and achieve the same by supporting the following options.
- option `-c` (compile) will output an object file (`*.o` or `*.obj`)
- option `-S` (assembly) will output an assembly file (`*.s`)
- option `-r` (run) will jit and run the input module
- no option will compile and link the file
Option `-o` will override the default name of the output file and, additionally, `--emit-llvm` will write a `*.bc` file in compile mode and a `*.ll` file in assembly mode.

Thus far the plan. Apart from introducing some of these options, I never implemented this functionality as the compiler currently does not support the full pipeline (including linking). Your fix seems fine for the time being!

**Comment by tenko** [comment]
Change implemented in pull request #19
