### ISSUE TITLE
Avoid writing .smb file for JITed main module

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#18]
I modified line 41 in Sema.cpp:

>     if (logger_.getErrorCount() == 0 && !config_.isJit()) {

This seems logical to add to me.

**Comment by zaskar9** [comment]
Yes, that's a reasonable change in my opinion. I was already getting annoyed by the `*.smb` files piling up in my `unittests` folder.

**Comment by tenko** [comment]
Excellent. Change implemented in pull request #19 .
