### ISSUE TITLE
Export of CHAR constants not supported

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#22]
The following code:

> MODULE Char ;
> CONST
>     NUL* = 00X;
>     TAB* = 09X;
>     LF*  = 0AX;
>     CR*  = 0DX;
>     SPC* = 020X;
> END Char.

Fails with:

> sym\Char.smb: error: Cannot export constant NUL*.
> sym\Char.smb: error: Cannot export constant TAB*.
> sym\Char.smb: error: Cannot export constant LF*.
> sym\Char.smb: error: Cannot export constant CR*.
> sym\Char.smb: error: Cannot export constant SPC*.
> Compilation failed: 5 error(s), 0 warning(s), 0 message(s).

It seems CHAR is not supported in symbol files.

**Comment by zaskar9** [comment]
Support for exporting and importing `CHAR` (and `SET`) constants has been added with the latest merged pull request.
