### ISSUE TITLE
CHAR variable not treated equal to CHAR literal

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#35]
Consider the following code:

```oberon
MODULE Test4;
(* Fails to compile in line 38 *)

PROCEDURE Length (str: ARRAY OF CHAR) : LONGINT;
VAR i: LONGINT;
BEGIN
    i := 0;
    WHILE (i < LEN(str)) & (str[i] # 00X) DO INC(i) END;
    RETURN i
END Length;

PROCEDURE Append(VAR dst : ARRAY OF CHAR; src : ARRAY OF CHAR);
VAR
    i, n: LONGINT;
    ch : CHAR;
BEGIN
    n := Length(dst);
    i := 0;
    ch := src[i];
    WHILE (ch # 00X) & (i < LEN(src)) & (i + n < LEN(dst)) DO
        dst[i + n] := ch;
        INC(i);
        ch := src[i]
    END
END Append;

PROCEDURE Test();
VAR
    str : ARRAY 32 OF CHAR;
    sch : ARRAY 1 OF CHAR;
    ch : CHAR;
BEGIN
    str := "test";
    sch := "1";
    ch := "3";
    Append(str, sch);
    Append(str, "2"); (* Char literal works *)
    Append(str, ch) (* Fails. Should probably work? *)
END Test;

BEGIN
    Test()
END Test4.
```

Should this work?

**Comment by zaskar9** [comment]
Line 38: `"2"` is treated a `STRING` literal in this case. Line 39: casting `CHAR` to `ARRAY OF CHAR` cannot happen implicitly. Everything is as it should be.

**Comment by tenko** [comment]
Very good.
I see XDS has this implicit cast from `CHAR` to `ARRAY OF CHAR`.

**Comment by zaskar9** [comment]
I thought about implementing such an implicit cast. However, if we started going down that road and tried to be general, every value could stand for the value itself and a one-element array containing that value. To me, that would be at odds with having a strongly typed language. 

The fact that `"2"` can be both a `CHAR` and a `STRING` (which is assignable to `ARRAY OF CHAR`) is a weakness, not a feature. Therefore, I decided to limit that flexibility to the plane of literals (using the internal type `STRING` that is not even available to the programmer).

**Comment by tenko** [comment]
Yes. There are corner cases as any language report is not 100% water tight.

I tested with [oberonjs](http://oberspace.org/oberonjs.html) which returns:
> line 38: type mismatch for argument 2: 'CHAR' cannot be converted to 'ARRAY OF CHAR'

The literal is OK, so this is most likely in line with other implementations. 

For the future I will try to setup OBNC for testing as the author is active on the Oberon mailing
list and is probably faithful to the language report.

**Comment by zaskar9** [comment]
> Otherwise it compiles. It also failed at runtime due to array out of bounds. I believe it is expecting ARRAY OF CHAR to always be NULL terminated and therefore fails when assigning a CHAR to an array with length 1.

That's precisely why I do not think that having this implicit conversion is a good idea and why the type system of `oberon-lang` distinguishes between `STRING` and `ARRAY OF CHAR`.
