### ISSUE TITLE
Small typo error in main.cpp

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#8]
Found this when building on MSYS2:
>   C:/msys64/home/rute/oberon-lang/src/main.cpp:97:36: error: expected ';' at end of declaration
>    97 |         std::string separator = ";"
>         |                                    ^
>         |                                    ;
>   1 error generated.

**Comment by zaskar9** [comment]
Fixed by ab86bcf8b6f927febb92970097355bb2a2e2713b.
